declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'
  export const Search: FC<SVGProps<SVGSVGElement>>
  export const Home: FC<SVGProps<SVGSVGElement>>
  export const FolderOpen: FC<SVGProps<SVGSVGElement>>
  export const Users: FC<SVGProps<SVGSVGElement>>
  export const Plus: FC<SVGProps<SVGSVGElement>>
  export const Play: FC<SVGProps<SVGSVGElement>>
  export const User: FC<SVGProps<SVGSVGElement>>
  export const ChevronDown: FC<SVGProps<SVGSVGElement>>
  export const MessageSquare: FC<SVGProps<SVGSVGElement>>
  export const Image: FC<SVGProps<SVGSVGElement>>
  export const Code: FC<SVGProps<SVGSVGElement>>
  export const Music: FC<SVGProps<SVGSVGElement>>
  export const Video: FC<SVGProps<SVGSVGElement>>
  export const FileText: FC<SVGProps<SVGSVGElement>>
  export const MoreHorizontal: FC<SVGProps<SVGSVGElement>>
  export const Send: FC<SVGProps<SVGSVGElement>>
  export const ArrowLeft: FC<SVGProps<SVGSVGElement>>
  export const Download: FC<SVGProps<SVGSVGElement>>
  export const X: FC<SVGProps<SVGSVGElement>>
  export const Maximize2: FC<SVGProps<SVGSVGElement>>
  export const Minimize2: FC<SVGProps<SVGSVGElement>>
  export const LogOut: FC<SVGProps<SVGSVGElement>>
  export const Sun: FC<SVGProps<SVGSVGElement>>
  export const Moon: FC<SVGProps<SVGSVGElement>>
  export const Sparkles: FC<SVGProps<SVGSVGElement>>
  export const Lock: FC<SVGProps<SVGSVGElement>>
  export const Mail: FC<SVGProps<SVGSVGElement>>
  export const Brain: FC<SVGProps<SVGSVGElement>>
  export const LogIn: FC<SVGProps<SVGSVGElement>>
  export const Clock: FC<SVGProps<SVGSVGElement>>
  export const Trash: FC<SVGProps<SVGSVGElement>>
  export const MessageCircle: FC<SVGProps<SVGSVGElement>>
  export const Loader: FC<SVGProps<SVGSVGElement>>
}